# Generated by Django 4.0.3 on 2022-03-18 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_newblogposts_update_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewBlogPosts',
            new_name='NewBlogPost',
        ),
    ]
