# Generated by Django 4.0.3 on 2022-03-17 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_rename_contact_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
    ]
